export const BOT_LIST_REQUEST = 'BOT_LIST_REQUEST';
export const BOT_LIST_SUCCESS = 'BOT_LIST_SUCCESS';
export const BOT_LIST_FAIL = 'BOT_LIST_FAIL';
// export const BOT_LIST_RESET = 'BOT_LIST_RESET';

export const BOT_ADD_REQUEST = 'BOT_ADD_REQUEST';
export const BOT_ADD_SUCCESS = 'BOT_ADD_SUCCESS';
export const BOT_ADD_FAIL = 'BOT_ADD_FAIL';

export const BOT_EDIT_REQUEST = 'BOT_EDIT_REQUEST';
export const BOT_EDIT_SUCCESS = 'BOT_EDIT_SUCCESS';
export const BOT_EDIT_FAIL = 'BOT_EDIT_FAIL';

export const BOT_DELETE_REQUEST = 'BOT_DELETE_REQUEST';
export const BOT_DELETE_SUCCESS = 'BOT_DELETE_SUCCESS';
export const BOT_DELETE_FAIL = 'BOT_DELETE_FAIL';
