export const DOCTOR_LIST_REQUEST = 'DOCTOR_LIST_REQUEST';
export const DOCTOR_LIST_SUCCESS = 'DOCTOR_LIST_SUCCESS';
export const DOCTOR_LIST_FAIL = 'DOCTOR_LIST_FAIL';
// export const DOCTOR_LIST_RESET = 'DOCTOR_LIST_RESET';

export const DOCTOR_ADD_REQUEST = 'DOCTOR_ADD_REQUEST';
export const DOCTOR_ADD_SUCCESS = 'DOCTOR_ADD_SUCCESS';
export const DOCTOR_ADD_FAIL = 'DOCTOR_ADD_FAIL';

export const DOCTOR_EDIT_REQUEST = 'DOCTOR_EDIT_REQUEST';
export const DOCTOR_EDIT_SUCCESS = 'DOCTOR_EDIT_SUCCESS';
export const DOCTOR_EDIT_FAIL = 'DOCTOR_EDIT_FAIL';

export const DOCTOR_DELETE_REQUEST = 'DOCTOR_DELETE_REQUEST';
export const DOCTOR_DELETE_SUCCESS = 'DOCTOR_DELETE_SUCCESS';
export const DOCTOR_DELETE_FAIL = 'DOCTOR_DELETE_FAIL';
