export const NURSES_LIST_REQUEST = 'NURSES_LIST_REQUEST';
export const NURSES_LIST_SUCCESS = 'NURSES_LIST_SUCCESS';
export const NURSES_LIST_FAIL = 'NURSES_LIST_FAIL';
export const NURSES_LIST_RESET = 'NURSES_LIST_RESET';

export const NURSE_ADD_REQUEST = 'NURSE_ADD_REQUEST';
export const NURSE_ADD_SUCCESS = 'NURSE_ADD_SUCCESS';
export const NURSE_ADD_FAIL = 'NURSE_ADD_FAIL';
export const NURSES_ADD_RESET = 'NURSES_ADD_RESET';

export const NURSES_EDIT_REQUEST = 'NURSES_EDIT_REQUEST';
export const NURSES_EDIT_SUCCESS = 'NURSES_EDIT_SUCCESS';
export const NURSES_EDIT_FAIL = 'NURSES_EDIT_FAIL';
export const NURSES_EDIT_RESET = 'NURSES_EDIT_RESET';

export const NURSES_DELETE_REQUEST = 'NURSES_DELETE_REQUEST';
export const NURSES_DELETE_SUCCESS = 'NURSES_DELETE_SUCCESS';
export const NURSES_DELETE_FAIL = 'NURSES_DELETE_FAIL';
export const NURSES_DELETE_RESET = 'NURSES_DELETE_RESET';
