export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST';
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL';
// export const PATIENT_LIST_RESET = 'PATIENT_LIST_RESET';

export const PATIENT_ADD_REQUEST = 'PATIENT_ADD_REQUEST';
export const PATIENT_ADD_SUCCESS = 'PATIENT_ADD_SUCCESS';
export const PATIENT_ADD_FAIL = 'PATIENT_ADD_FAIL';

export const PATIENT_EDIT_REQUEST = 'PATIENT_EDIT_REQUEST';
export const PATIENT_EDIT_SUCCESS = 'PATIENT_EDIT_SUCCESS';
export const PATIENT_EDIT_FAIL = 'PATIENT_EDIT_FAIL';

export const PATIENT_DELETE_REQUEST = 'PATIENT_DELETE_REQUEST';
export const PATIENT_DELETE_SUCCESS = 'PATIENT_DELETE_SUCCESS';
export const PATIENT_DELETE_FAIL = 'PATIENT_DELETE_FAIL';
// Patient Report particular dates
export const PATIENT_REPORT_LIST_ON_DATE_REQUEST = 'PATIENT_REPORT_LIST_ON_DATE_REQUEST';
export const PATIENT_REPORT_LIST_ON_DATE_SUCCESS = 'PATIENT_REPORT_LIST_ON_DATE_SUCCESS';
export const PATIENT_REPORT_LIST_ON_DATE_FAIL = 'PATIENT_REPORT_LIST_ON_DATE_FAIL';

// For Patient Report
export const PATIENT_REPORT_REQUEST = 'PATIENT_REPORT_REQUEST';
export const PATIENT_REPORT_SUCCESS = 'PATIENT_REPORT_SUCCESS';
export const PATIENT_REPORT_FAIL = 'PATIENT_REPORT_FAIL';

export const ALL_DOCTORS_AGAINST_PATIENT_REQUEST = 'ALL_DOCTORS_AGAINST_PATIENT_REQUEST';
export const ALL_DOCTORS_AGAINST_PATIENT_SUCCESS = 'ALL_DOCTORS_AGAINST_PATIENT_SUCCESS';
export const ALL_DOCTORS_AGAINST_PATIENT_FAIL = 'ALL_DOCTORS_AGAINST_PATIENT_FAIL';

export const POST_DOC_IDS_REQUEST = 'POST_DOC_IDS_REQUEST';
export const POST_DOC_IDS_SUCCESS = 'POST_DOC_IDS_SUCCESS';
export const POST_DOC_IDS_FAIL = 'POST_DOC_IDS_FAIL';
